// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: public/double-api/v1/test.proto

package httpdoc

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProtoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32                      `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name    string                     `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Active  bool                       `protobuf:"varint,3,opt,name=Active,proto3" json:"Active,omitempty"`
	Setting *UserProtoResponse_Setting `protobuf:"bytes,4,opt,name=Setting,proto3" json:"Setting,omitempty"`
}

func (x *UserProtoResponse) Reset() {
	*x = UserProtoResponse{}
	mi := &file_public_double_api_v1_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProtoResponse) ProtoMessage() {}

func (x *UserProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_double_api_v1_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProtoResponse.ProtoReflect.Descriptor instead.
func (*UserProtoResponse) Descriptor() ([]byte, []int) {
	return file_public_double_api_v1_test_proto_rawDescGZIP(), []int{0}
}

func (x *UserProtoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProtoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProtoResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UserProtoResponse) GetSetting() *UserProtoResponse_Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type UserProtoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *UserProtoRequest) Reset() {
	*x = UserProtoRequest{}
	mi := &file_public_double_api_v1_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProtoRequest) ProtoMessage() {}

func (x *UserProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_double_api_v1_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProtoRequest.ProtoReflect.Descriptor instead.
func (*UserProtoRequest) Descriptor() ([]byte, []int) {
	return file_public_double_api_v1_test_proto_rawDescGZIP(), []int{1}
}

func (x *UserProtoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProtoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserProtoResponse_Setting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *UserProtoResponse_Setting) Reset() {
	*x = UserProtoResponse_Setting{}
	mi := &file_public_double_api_v1_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProtoResponse_Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProtoResponse_Setting) ProtoMessage() {}

func (x *UserProtoResponse_Setting) ProtoReflect() protoreflect.Message {
	mi := &file_public_double_api_v1_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProtoResponse_Setting.ProtoReflect.Descriptor instead.
func (*UserProtoResponse_Setting) Descriptor() ([]byte, []int) {
	return file_public_double_api_v1_test_proto_rawDescGZIP(), []int{2}
}

func (x *UserProtoResponse_Setting) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_public_double_api_v1_test_proto protoreflect.FileDescriptor

var file_public_double_api_v1_test_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x76, 0x31, 0x22, 0x8e, 0x01, 0x0a, 0x11,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x3d, 0x0a,
	0x07, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x07, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x36, 0x0a, 0x10,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x99, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x76, 0x31, 0x42, 0x09, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x6f, 0x75, 0x7a, 0x6f, 0x68, 0x2f, 0x6d, 0x65, 0x72, 0x63, 0x61, 0x72, 0x69,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x75, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f,
	0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x44, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x76, 0x31, 0xca, 0x02, 0x08, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x76,
	0x31, 0xe2, 0x02, 0x14, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x76, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_public_double_api_v1_test_proto_rawDescOnce sync.Once
	file_public_double_api_v1_test_proto_rawDescData = file_public_double_api_v1_test_proto_rawDesc
)

func file_public_double_api_v1_test_proto_rawDescGZIP() []byte {
	file_public_double_api_v1_test_proto_rawDescOnce.Do(func() {
		file_public_double_api_v1_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_public_double_api_v1_test_proto_rawDescData)
	})
	return file_public_double_api_v1_test_proto_rawDescData
}

var file_public_double_api_v1_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_public_double_api_v1_test_proto_goTypes = []any{
	(*UserProtoResponse)(nil),         // 0: doublev1.UserProtoResponse
	(*UserProtoRequest)(nil),          // 1: doublev1.UserProtoRequest
	(*UserProtoResponse_Setting)(nil), // 2: doublev1.UserProtoResponse_Setting
}
var file_public_double_api_v1_test_proto_depIdxs = []int32{
	2, // 0: doublev1.UserProtoResponse.Setting:type_name -> doublev1.UserProtoResponse_Setting
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_public_double_api_v1_test_proto_init() }
func file_public_double_api_v1_test_proto_init() {
	if File_public_double_api_v1_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_public_double_api_v1_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_double_api_v1_test_proto_goTypes,
		DependencyIndexes: file_public_double_api_v1_test_proto_depIdxs,
		MessageInfos:      file_public_double_api_v1_test_proto_msgTypes,
	}.Build()
	File_public_double_api_v1_test_proto = out.File
	file_public_double_api_v1_test_proto_rawDesc = nil
	file_public_double_api_v1_test_proto_goTypes = nil
	file_public_double_api_v1_test_proto_depIdxs = nil
}
